version: '3.8'
services:
  bags:
    image: manikantabuddepu/bags:latest
    ports:
      - "85:80"
    deploy:
      replicas: 3
  books:
    image: manikantabuddepu/books:latest
    ports:
      - "86:80"
    deploy:
      replicas: 3
  pens:
    image: manikantabuddepu/pens:latest
    ports:
      - "87:80"
    deploy:
      replicas: 3
  boxs:
    image: manikantabuddepu/boxs:latest
    ports:
      - "88:80"
    deploy:
      replicas: 3
